version: "3"

services:
   trifid: 
      image: ghcr.io/zazuko/trifid
      ports:
         - "8080:8080"
      environment:
         SPARQL_ENDPOINT_URL: "http://localhost:3030/blazegraph/namespace/um/sparql"
         DATASET_BASE_URL: "https://um.es/"