version: "3"
services:
   linked_data_server:
      image: ghcr.io/zazuko/trifid
      ports:
         - "8080:8080"
      environment:
         SPARQL_ENDPOINT_URL: "http://sparql_endpoint:7878/query"
         DATASET_BASE_URL: "http://fair/data/"

   sparql_endpoint:
      image: ghcr.io/oxigraph/oxigraph
      volumes:
         - ./oxigraph/data:/data
      ports:
         - "7878:7878"